### ISSUE TITLE
Split global.image variable to global.image and global.tag

### ISSUE THREAD

**Issue by igor-pinchuk** [hashicorp/consul-k8s#2510] opened 2023-07-05 17:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.
Consul Helm chart has variables that allow overriding images, e.g. `global.image`, these variables  contain image repository address and image tag separated by colon.
It does not work very well with pull-through cache as we need to override only image address part and leave default tag value as is.
So each time we are updating Helm chart version we need to make sure that we also updated all image tags to newer versions.
It gets especially annoying when you manage multiple envs with different version of Consul and have to track all those tags.

#### Feature Description

If we had two variables:
`global.image`
and 
`global.tag`
that would make pull-through cache integration very smooth as only `global.image` would have to be overwritten once and `global.tag` would always be default.
#### Use Case(s)

This is relevant for all variables that contain both registry address and tag in the same variable.
#### Contributions

Yes, I can provide a PR to address this issue

**Comment by david-yu** [comment] 2023-07-05 18:30
Hi @igor-pinchuk this is a duplicate of https://github.com/hashicorp/consul-k8s/issues/644. I'll go ahead and close so we can track there. Right now this would introduce a lot of changes for the integration testing side of Consul-k8s so we've delayed working on this as it is a breaking change.

**Closed by david-yu** 2023-07-05 18:30 UTC
Labels: type/enhancement
