### ISSUE TITLE
After upgrading to K8s 1.21 on EKS, consul-sync-catalog pod in CrashLoopBackOff and consul-server fails to start

### ISSUE THREAD

**Issue by Throckmortra** [hashicorp/consul-k8s#939] opened 2021-12-22 20:14 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Previously I was running Consul-Helm on EKS Kubernetes 1.19 successfully. After running into some issues with aws-load-balancer-controller NLBs, I decided to try upgrading my cluster and redeploying consul-helm fresh (after deleting the namespace) 

When attempting to redeploy Consul after the upgrade, the server pods fail to come up and consul-sync-catalog pod is in a crash loop with the following error: 

```
consul-sync-catalog
Error retrieving Kubernetes auth: 2 errors occurred:
consul-sync-catalog
    * error loading kubeconfig: stat /home/100/.kube/config: no such file or directory
consul-sync-catalog
    * error loading in-cluster config: open /var/run/secrets/kubernetes.io/serviceaccount/token: permission denied
```

Note: I was previously deleting and redeploying this over and over successfully on 1.19. (in my attempts to get exposeGossipAndRPCPorts option to work with NLB)

### Reproduction Steps

1. When running helm install with the following `values.yml`:
```
global:
  datacenter: consul
  acls:
    manageSystemACLs: false
    createReplicationToken: false

ui:
  enabled: true
  service:
    type: NodePort

syncCatalog:
  enabled: true

server:
  replicas: 2
  bootstrapExpect: 2
  exposeGossipAndRPCPorts: true
  ports:
    serflan:
      port: 9301

client:
  enabled: false
```
1. Upgrade an EKS cluster from 1.19 -> 1.20 -> 1.21
2. attempt a fresh install of Consul
`helm install consul hashicorp/consul --set global.name=consul --create-namespace -n consul -f consul-server.yml`

### Logs

<details>
  <summary>Logs</summary>

```
consul-sync-catalog
Error retrieving Kubernetes auth: 2 errors occurred:
consul-sync-catalog
    * error loading kubeconfig: stat /home/100/.kube/config: no such file or directory
consul-sync-catalog
    * error loading in-cluster config: open /var/run/secrets/kubernetes.io/serviceaccount/token: permission denied
```

</details>

### Expected behavior

consul to deploy successfully

### Environment details

EKS Kubernetes version: 1.21 eks.4
Consul-k8s version: 0.37.0

**Comment by Throckmortra** [comment] 2021-12-22 21:40
this looks related: https://github.com/metallb/metallb/issues/890

**Comment by Throckmortra** [comment] 2021-12-26 17:52
just to rule it out, I tried running it on an older EKS cluster running K8s 1.18 and it deployed successfully

**Comment by ishustava** [comment] 2022-01-04 01:13
Hey @Throckmortra 

I've tried it on EKS `v1.21.2-eks-06eac09`, and was not able to reproduce. 

Why do the server pods fail to come up? Could you post server logs? Could you also include the output of `kubectl get pods`?

**Comment by Throckmortra** [comment] 2022-01-04 17:50
They are stuck in pending due to:
`[Unschedulable] 0/2 nodes are available: 2 node(s) had volume node affinity conflict.`

output:
```
NAME              READY   STATUS    RESTARTS   AGE
consul-server-0   0/1     Pending   0          12d
consul-server-1   0/1     Pending   0          12d
```

**Comment by ishustava** [comment] 2022-01-04 19:12
It looks like you need to fix ` 2 node(s) had volume node affinity conflict.` error. The catalog-sync error you've posted before looks strange but could be a red herring once you fix the servers. As I mentioned in my previous comment, I was not able to reproduce on a clean EKS cluster. Could you try it on a new cluster and see if this error occurs again?

**Comment by david-yu** [comment] 2022-02-23 05:37
Hi @Throckmortra closing, let us know if the last response did not help and re-open.

**Closed by david-yu** 2022-02-23 05:37 UTC
Labels: type/bug, waiting-reply
