### ISSUE TITLE
How to sync 2 endpoint using host network with different port

### ISSUE THREAD

**Issue by vietkute02** [hashicorp/consul-k8s#572] opened 2021-07-27 10:48 UTC
#### Question
Hi all,
I've problem when try to sync (merge) 2 endpoint from 2 k8s service with same consul service annotation config
- 2 endpoint (pod) using host network and expose different port

Behavior: 
- Instance Id is duplicate (I think it base in pod Ip)
- Only one Instance sync to consul

Version: 
- consul-k8s:0.18.1

please help me to solve this problem. Thanks very much

English is not my mother tongue; please excuse any errors on my part

**Comment by ndhanushkodi** [comment] 2021-07-29 23:23
Hi @vietkute02, currently Consul does not support associating multiple ports to a single service. The 2 Pods would need to share the same port in order to work right now. We are tracking this feature in this issue [here](https://github.com/hashicorp/consul/issues/5388). Feel free to give that issue a :+1: to show your interest in that feature, and leave a comment with any additional details that might help us better understand your use case. 

In the meanwhile, we'll close this as a duplicate of that issue, but please feel free to reopen this if you have other questions or if we misunderstood your use case. Thank you!!

- Nitya and @sadjamz

**Closed by ndhanushkodi** 2021-07-29 23:23 UTC
Labels: question
