### ISSUE TITLE
Add /quitquitquit endpoint to lifecycle sidecar/envoy so Jobs can self-terminate their sidecars

### ISSUE THREAD

**Issue by sylvainOL** [hashicorp/consul-k8s#162] opened 2019-10-24 06:56 UTC
#### Overview of the Issue

When using job, `consul-connect-envoy-sidecar` makes them running forever even when the Job container is in `Terminated` status.

#### Reproduction Steps

1. Create a cluster and install consul connect via helm with this override:

   ```yaml
   ---
   global:
     enabled: true

   server:
     replicas: 1
     bootstrapExpect: 1
     connect: true
     storageClass: nfs-client

   client:
     grpc: true

   ui:
     enabled: true

   connectInject:
     enabled: true
     default: true
     centralConfig:
       enabled: true
       defaultProtocol: http
   ```

2. Create a Job file `job.yml`:

   ```yaml
   ---
   apiVersion: batch/v1
   kind: Job
   metadata:
     name: pi
   spec:
     template:
       spec:
         containers:
         - name: pi
           image: perl
           command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
         restartPolicy: Never
     backoffLimit: 4
   ```

3. Apply: `kubectl apply -f job.yml`
4. Wait a little bit
5. look at the job `kubectl describe po -ljob-name=pi`:

  ```yaml
  Name:           pi-7znmn
  Namespace:      default
  Priority:       0
  Node:           compute02-test-2/10.253.0.9
  Start Time:     Thu, 24 Oct 2019 06:39:05 +0000
  Labels:         controller-uid=a5b8429c-44ed-48ae-bb81-82ff12772ffe
                  job-name=pi
  Annotations:    consul.hashicorp.com/connect-inject-status: injected
                  consul.hashicorp.com/connect-service: pi
                  consul.hashicorp.com/connect-service-protocol: http
  Status:         Running
  IP:             10.233.67.186
  Controlled By:  Job/pi
  Init Containers:
    consul-connect-inject-init:
      Container ID:  docker://a7ef1cf9a296912b66110691345e1872f86368caaab8b3a88e200f4a71b5b8eb
      Image:         consul:1.6.1
      Image ID:      docker-pullable://consul@sha256:94cdbd83f24ec406da2b5d300a112c14cf1091bed8d6abd49609e6fe3c23f181
      Port:          <none>
      Host Port:     <none>
      Command:
        /bin/sh
        -ec
        export CONSUL_HTTP_ADDR="${HOST_IP}:8500"
        export CONSUL_GRPC_ADDR="${HOST_IP}:8502"

        # Register the service. The HCL is stored in the volume so that
        # the preStop hook can access it to deregister the service.
        cat <<EOF >/consul/connect-inject/service.hcl
        services {
          id   = "${POD_NAME}-pi-sidecar-proxy"
          name = "pi-sidecar-proxy"
          kind = "connect-proxy"
          address = "${POD_IP}"
          port = 20000

          proxy {
            destination_service_name = "pi"
            destination_service_id = "pi"
          }

          checks {
            name = "Proxy Public Listener"
            tcp = "${POD_IP}:20000"
            interval = "10s"
            deregister_critical_service_after = "10m"
          }

          checks {
            name = "Destination Alias"
            alias_service = "pi"
          }
        }

        services {
          id   = "${POD_NAME}-pi"
          name = "pi"
          address = "${POD_IP}"
          port = 0
        }
        EOF
        # Create the central config's service registration
        cat <<EOF >/consul/connect-inject/central-config.hcl
        kind = "service-defaults"
        name = "pi"
        protocol = "http"
        EOF
        /bin/consul config write -cas -modify-index 0 \
          /consul/connect-inject/central-config.hcl || true

        /bin/consul services register \
          /consul/connect-inject/service.hcl

        # Generate the envoy bootstrap code
        /bin/consul connect envoy \
          -proxy-id="${POD_NAME}-pi-sidecar-proxy" \
          -bootstrap > /consul/connect-inject/envoy-bootstrap.yaml

        # Copy the Consul binary
        cp /bin/consul /consul/connect-inject/consul
      State:          Terminated
        Reason:       Completed
        Exit Code:    0
        Started:      Thu, 24 Oct 2019 06:39:08 +0000
        Finished:     Thu, 24 Oct 2019 06:39:08 +0000
      Ready:          True
      Restart Count:  0
      Environment:
        HOST_IP:         (v1:status.hostIP)
        POD_IP:          (v1:status.podIP)
        POD_NAME:       pi-7znmn (v1:metadata.name)
        POD_NAMESPACE:  default (v1:metadata.namespace)
      Mounts:
        /consul/connect-inject from consul-connect-inject-data (rw)
        /var/run/secrets/kubernetes.io/serviceaccount from default-token-p4ntz (ro)
  Containers:
    pi:
      Container ID:  docker://f57e3a3abd0ef2cc35b563e65e047398eba8126e68ce6e6ddd4cfb7835d02733
      Image:         perl
      Image ID:      docker-pullable://perl@sha256:b3f356876d5615e91b808cbdcba0ff618a7ba0c167326bd013c15b2194db03c9
      Port:          <none>
      Host Port:     <none>
      Command:
        perl
        -Mbignum=bpi
        -wle
        print bpi(2000)
      State:          Terminated
        Reason:       Completed
        Exit Code:    0
        Started:      Thu, 24 Oct 2019 06:39:24 +0000
        Finished:     Thu, 24 Oct 2019 06:39:30 +0000
      Ready:          False
      Restart Count:  0
      Environment:    <none>
      Mounts:
        /var/run/secrets/kubernetes.io/serviceaccount from default-token-p4ntz (ro)
    consul-connect-envoy-sidecar:
      Container ID:  docker://9d8ec302199ad5271196356140dd20b204e67c56f8036a6b51173a1395d81b77
      Image:         envoyproxy/envoy-alpine:v1.9.1
      Image ID:      docker-pullable://envoyproxy/envoy-alpine@sha256:04ed416733b49260db0a346565ab523c6d2a362cfd29a1ab23a926af77849ecb
      Port:          <none>
      Host Port:     <none>
      Command:
        envoy
        --max-obj-name-len
        256
        --config-path
        /consul/connect-inject/envoy-bootstrap.yaml
      State:          Running
        Started:      Thu, 24 Oct 2019 06:39:25 +0000
      Ready:          True
      Restart Count:  0
      Environment:
        HOST_IP:   (v1:status.hostIP)
      Mounts:
        /consul/connect-inject from consul-connect-inject-data (rw)
        /var/run/secrets/kubernetes.io/serviceaccount from default-token-p4ntz (ro)
  Conditions:
    Type              Status
    Initialized       True
    Ready             False
    ContainersReady   False
    PodScheduled      True
  Volumes:
    default-token-p4ntz:
      Type:        Secret (a volume populated by a Secret)
      SecretName:  default-token-p4ntz
      Optional:    false
    consul-connect-inject-data:
      Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
      Medium:
      SizeLimit:   <unset>
  QoS Class:       BestEffort
  Node-Selectors:  <none>
  Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                   node.kubernetes.io/unreachable:NoExecute for 300s
  Events:
    Type    Reason     Age    From                       Message
    ----    ------     ----   ----                       -------
    Normal  Scheduled  4m44s  default-scheduler          Successfully assigned default/pi-7znmn to compute02-test-2
    Normal  Pulled     4m41s  kubelet, compute02-test-2  Container image "consul:1.6.1" already present on machine
    Normal  Created    4m41s  kubelet, compute02-test-2  Created container consul-connect-inject-init
    Normal  Started    4m41s  kubelet, compute02-test-2  Started container consul-connect-inject-init
    Normal  Pulling    4m41s  kubelet, compute02-test-2  Pulling image "perl"
    Normal  Pulled     4m25s  kubelet, compute02-test-2  Successfully pulled image "perl"
    Normal  Created    4m25s  kubelet, compute02-test-2  Created container pi
    Normal  Started    4m25s  kubelet, compute02-test-2  Started container pi
    Normal  Pulled     4m25s  kubelet, compute02-test-2  Container image "envoyproxy/envoy-alpine:v1.9.1" already present on machine
    Normal  Created    4m25s  kubelet, compute02-test-2  Created container consul-connect-envoy-sidecar
    Normal  Started    4m24s  kubelet, compute02-test-2  Started container consul-connect-envoy-sidecar
  ```  

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```shell
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 62
	services = 62
build:
	prerelease =
	revision = 9be6dfc3
	version = 1.6.1
consul:
	acl = disabled
	known_servers = 1
	server = false
runtime:
	arch = amd64
	cpu_count = 32
	goroutines = 590
	max_procs = 32
	os = linux
	version = go1.12.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 5
	members = 4
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```shell
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 9be6dfc3
	version = 1.6.1
consul:
	acl = disabled
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 10.233.65.27:8300
	server = true
raft:
	applied_index = 10031
	commit_index = 10031
	fsm_pending = 0
	last_contact = 0
	last_log_index = 10031
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:53bfea2a-aa00-2ee2-13c5-c9b682e903f9 Address:10.233.65.27:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 32
	goroutines = 345
	max_procs = 32
	os = linux
	version = go1.12.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 5
	members = 4
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

* OS: Debian 9
* Kubernetes: 1.15.3
* Helm: 2.14.3
* Installer: Kubespray
* CNI: cilium

**Comment by adilyse** [comment] 2019-11-07 01:40
Hi @sylvainOL,

Do you need this job to run with Connect? If not, you can add [`"consul.hashicorp.com/connect-inject": "false"`](https://www.consul.io/docs/platform/k8s/connect.html#consul-hashicorp-com-connect-inject) to the annotations in your job spec and the injector won't create a sidecar which will allow the job to terminate normally.

**Comment by sylvainOL** [comment] 2019-11-07 08:05
Hi @adilyse, I've seen after that's a "common" service mesh issue (https://github.com/linkerd/linkerd2/issues/1869, https://github.com/istio/istio/issues/6324, ...).
I think there should be a "clean" answer to this issue but as of today, annotation injection is what I do :)

**Comment by adilyse** [comment] 2019-11-08 19:24
Glad to hear that the annotation will work for you! Going to close this now, but we'll keep this in mind as we continue to improve Connect in Kubernetes.

**Comment by Spaceman1861** [comment] 2019-12-10 01:45
@adilyse I have the same problem but I require Connet to be active on the jobs.

I havent been able to come up with a solution that doesnt involve another job polling for jobs that should be killed.

I want to know how to override the side car with a script that polls for active connections like.
https://github.com/istio/istio/issues/15041

At the end of the job I can just call 
curl --data "" 127.0.0.1:19000/quitquitquit

Ill post my progress here but it would be good to know if there is a solution for this thats not just turning it off.

**Comment by lkysow** [comment] 2019-12-10 18:08
Hey Sean, good idea. Let us know how you do and if you could create a new issue to track that would be awesome!

**Comment by Spaceman1861** [comment] 2019-12-11 02:37
So I have implemented I super hacky workaround for now, which ill post here if anyone can find use of it.

Its is a powershell script that runs on a machine with kubectl access.

I will endeavor to commit some time a less hacky solution.

When I do I will spin up a new issue.

```
while(1){
    $time = Get-Date
    Write-Output $time
    $pods = kubectl get pods -n live
    foreach ($pod in $pods) {

        if($pod.StartsWith('nameofservice') -and $pod.Contains('1/2')){
            Write-Output $pod
            $tar = $pod.Substring(0,$pod.IndexOf(' '));
            Write-Output "deleting $tar"

            kubectl exec $tar -n live -c consul-connect-envoy-sidecar kill 1
        }
    }

    Start-Sleep -Seconds 60
}
```

**Comment by Lord-Y** [comment] 2020-11-05 12:18
@lkysow I have exactly the same problem and I need the sidecar to connect to my database. I executed the curl command from @Spaceman1861 but the `consul-connect-lifecycle-sidecar` pod is still up. Any better implementation than last post of @Spaceman1861 like adding an another annotation?

**Comment by ishustava** [comment] 2020-11-06 00:49
@Lord-Y I think you're right. 

Some thoughts on solutions to this:
1. Provide a way to not inject the lifecycle-sidecar based on some annotation
1. Add an API to the lifecycle sidecar so that we you can terminate it when the job is done just like you can do with envoy

It sounds like there could be a workaround as mentioned in [this comment](https://github.com/istio/istio/issues/6324#issuecomment-457742042) where you can share the process namespace and call `pkill` on the lifecycle sidecar process.

Also, as mentioned in [this comment](https://github.com/istio/istio/issues/6324#issuecomment-533923427), it could be hard for us to provide a good UX without support from Kubernetes itself because there's no way to express dependency relationships between containers in a pod.

**Comment by Spaceman1861** [comment] 2020-11-06 00:57
@Lord-Y I think in the end we removed consul registration for the cron job and went down another path. We had another pod that acted as a gateway and we routed traffic thru it via the kubernetes dns.

**Comment by magickatt** [comment] 2020-11-24 22:22
We came across this issue and this is the (not ideal) way we're dealing with it at the moment. Would definitely be curious what other ways there might be to solve the issue for sure!

We are sharing process namespaces and using the primary container to kill the sidecars before exit.

```
shareProcessNamespace: true
containers:
- name: "busybox"
  image: "python"
  command:
  [
    "/bin/bash",
    "-c",
    "something && kill $(pidof envoy) && kill -2 $(pidof consul-k8s) && exit 0",
  ]
  securityContext:
    capabilities:
      add:
        - SYS_PTRACE

**Comment by Spaceman1861** [comment] 2020-11-26 02:59
That is a much better solution 👍

**Comment by lkysow** [comment] 2020-11-28 00:02
So if we implemented `/quitquitquit` then you'd have something like:
```yaml: true
containers:
- name: "something"
  image: "busybox"
  command:
  [
    "/bin/bash",
    "-c",
    "something && curl localhost:19999/quitquitquit && exit 0",
  ]
```

**Comment by Lord-Y** [comment] 2020-11-30 20:06
@lkysow yes but an annotation must be added to prevent lifecycle sidecar unless /quitquitquit deregister it

**Comment by lkysow** [comment] 2020-12-04 17:29
> @lkysow yes but an annotation must be added to prevent lifecycle sidecar unless /quitquitquit deregister it

Sorry, can you expand on what you mean by this?

**Comment by Lord-Y** [comment] 2020-12-16 15:37
> > @lkysow yes but an annotation must be added to prevent lifecycle sidecar unless /quitquitquit deregister it
> 
> Sorry, can you expand on what you mean by this?

@lkysow sorry for the very late answer. My pod is composed of 3 containers:
- db-migration
- consul-connect-envoy-sidecar
- consul-connect-lifecycle-sidecar

By doing a POST to /quitquitquit, only the container consul-connect-envoy-sidecar will be softly killed.
The problem is the container consul-connect-lifecycle-sidecar will stay forever which mean that the pod will still running.

In order to solve the problem, what can be done is:
- make an annotation in order to prevent the injection of the container consul-connect-lifecycle-sidecar like consul.hashicorp.com/lifecycle-sidecar: 'false' and POST /quitquitquit to the container consul-connect-envoy-sidecar will be perfect
- or with you do POST /endpoint/quitquitquit (not envoy endpoint directly),both containers consul-connect-envoy-sidecar and consul-connect-lifecycle-sidecar will be killed

So far I'm bypassing connect-inject on my db migration.
I hope my explaination is more clear :-)

I personnally dont' want to add shareProcessNamespace  in my pod. I prefer a more clean solution

**Comment by lkysow** [comment] 2020-12-16 23:21
Gotcha yeah this makes sense. Probably we should implement `/quitquitquit` in the lifecycle sidecar and then that would also make the call to envoy.

**Comment by HofmannZ** [comment] 2021-02-03 00:32
Any progress on this issue? :)

**Comment by ndhanushkodi** [comment] 2021-02-03 02:42
Hi @HofmannZ it is on the radar but probably would take a while to get to it given the current workload and priority on the team. We would totally be open to contribution in the meantime!

**Comment by lkysow** [comment] 2021-09-02 21:31
Hi, we actually don't have the lifecycle sidecar anymore. There's just the envoy sidecar so I don't think this is required now.

**Closed by lkysow** 2021-09-02 21:31 UTC
Labels: enhancement, area/connect

**Comment by curtbushko** [comment] 2023-07-11 18:17
As part of consul-k8s releases [1.0.8](https://github.com/hashicorp/consul-k8s/releases/tag/v1.0.8) and [1.1.3](https://github.com/hashicorp/consul-k8s/releases/tag/v1.1.3) we added support for graceful shutdown in the proxy lifecycle. The next 1.2.x release that comes out will also have this feature enabled.

With it the feature, you can call `/graceful_shutdown` on the proxy and it will terminate consul-dataplane.

An example of how to use `/graceful_shutdown` can be seen in the [jobs example](https://developer.hashicorp.com/consul/docs/k8s/connect#kubernetes-jobs) on our website.

The most important piece is that you can curl the endpoint:
```
curl --max-time 2 -s -f -XPOST http://127.0.0.1:20600/graceful_shutdown
```
