### ISSUE TITLE
Services deployed in service mesh are unable to communicate with default kubernetes service on port 443

### ISSUE THREAD

**Issue by codex70** [hashicorp/consul-k8s#1848] opened 2023-01-23 16:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Overview of the Issue

Spring boot services deployed in the Consul Service Mesh are unable to connect with the default kubernetes service on port 443. Because of this, Spring Cloud Kubernetes does not work, and we are unable to load the service config file.

Also, Spring Cloud Consul is unable to connect to consul using the following configuration for Spring Cloud:
```
spring:
  cloud:
    consul:
      enabled: true
      host: "${HOST_IP}"
      port: 8501
      scheme: "HTTPS"
```

Finally, I am unable to connect to any of the services using nginx ingress, all service mesh services return a 502 error, even those that appear to be running correctly. 

This is all with consul deployed using helm template `1.0.2`. All of these systems work perfectly without issue using helm template `0.49.2`

### Reproduction Steps

Deploy consul using the following helm values:
```
global:
  name: consul
  datacenter: dc1
  metrics:
    enabled: true
  federation:
    enabled: true
    createFederationSecret: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
    serverAdditionalDNSSANs:
      ## Add the K8s domain name to the consul server certificate
      - "consul-server-0.consul.svc.cluster.local"
      - "consul-server-1.consul.svc.cluster.local"
      - "consul-server-2.consul.svc.cluster.local"
      - "consul-server.consul.svc.cluster.local"
      - "consul.consul.svc.cluster.local"
      - "consul.service.consul"

  ## For production turn on ACLs and gossipEncryption:
  acls:
    manageSystemACLs: true
    createReplicationToken: true
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

server:
  replicas: 3
  securityContext:
    runAsNonRoot: false
    runAsUser: 0

# see https://www.consul.io/docs/connect/observability/ui-visualization#configuring-dashboard-urls
# currently cross dataceter is not supported, even though it would likely work using Thanos....
ui:
  enabled: true
  metrics:
    enabled: true
  service:
    type: NodePort
    nodePort:
      http: 31689
      https: 30448

connectInject:
  # This method will inject the sidecar container into Pods:
  enabled: true
  # But not by default, only do this for Pods that have the explicit annotation:
  #        consul.hashicorp.com/connect-inject: "true"
  default: false
meshGateway:
  enabled: true

syncCatalog:
  enabled: true
  default: true
  toConsul: true
  toK8S: true
  syncClusterIPServices: false

apiGateway:
  enabled: true
  image: "hashicorp/consul-api-gateway:1.5.0"
  logLevel: debug
  managedGatewayClass:
    enabled: true
    serviceType: LoadBalancer
    useHostPorts: true
```

### Logs

The following are logs from the failing spring boot services:

```
class io.kubernetes.client.openapi.models.V1Endpoints#Reflector loop failed unexpectedly
java.lang.IllegalStateException: java.net.ConnectException: Failed to connect to /10.42.0.1:443
	at io.kubernetes.client.util.generic.GenericKubernetesApi.executeCall(GenericKubernetesApi.java:793)
	at io.kubernetes.client.util.generic.GenericKubernetesApi.list(GenericKubernetesApi.java:337)
	at io.kubernetes.client.informer.SharedInformerFactory$2.list(SharedInformerFactory.java:235)
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:88)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)\nCaused by: java.net.ConnectException: Failed to connect to /10.42.0.1:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.kubernetes.client.util.credentials.TokenFileAuthentication.intercept(TokenFileAuthentication.java:72)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:885)
	at io.kubernetes.client.util.generic.GenericKubernetesApi.executeCall(GenericKubernetesApi.java:789)
	... 9 common frames omitted\nCaused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 28 common frames omitted\n"}

failed invoking ADD event handler: {}
java.lang.NullPointerException: Cannot invoke \"org.springframework.boot.SpringApplication.getEnvironmentPrefix()\" because \"application\" is null
	at org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor.postProcessEnvironment(SystemEnvironmentPropertySourceEnvironmentPostProcessor.java:55)
	at org.springframework.cloud.context.refresh.ConfigDataContextRefresher.updateEnvironment(ConfigDataContextRefresher.java:92)
	at org.springframework.cloud.context.refresh.ContextRefresher.refreshEnvironment(ContextRefresher.java:101)
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:94)
	at org.springframework.cloud.kubernetes.commons.config.reload.ConfigurationChangeDetector.reloadProperties(ConfigurationChangeDetector.java:51)
	at org.springframework.cloud.kubernetes.client.config.reload.KubernetesClientEventBasedConfigMapChangeDetector.onEvent(KubernetesClientEventBasedConfigMapChangeDetector.java:153)
	at org.springframework.cloud.kubernetes.client.config.reload.KubernetesClientEventBasedConfigMapChangeDetector$1.onAdd(KubernetesClientEventBasedConfigMapChangeDetector.java:75)
	at org.springframework.cloud.kubernetes.client.config.reload.KubernetesClientEventBasedConfigMapChangeDetector$1.onAdd(KubernetesClientEventBasedConfigMapChangeDetector.java:70)
	at io.kubernetes.client.informer.cache.ProcessorListener.run(ProcessorListener.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)\n"}

Error watching Consul CatalogServices
com.ecwid.consul.transport.TransportException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:83)
	at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:36)
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:139)
	at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogServices(CatalogConsulClient.java:143)
	at com.ecwid.consul.v1.ConsulClient.getCatalogServices(ConsulClient.java:400)
	at org.springframework.cloud.consul.discovery.ConsulCatalogWatch.catalogServicesWatch(ConsulCatalogWatch.java:130)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)\nCaused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:70)
	... 12 common frames omitted
	Suppressed: java.net.SocketException: Broken pipe
	\tat java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
	\tat java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
	\tat java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
	\tat java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
	\tat java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(Unknown Source)
	\tat java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	\tat java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	\t... 29 common frames omitted\nCaused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	... 31 common frames omitted\n"}
```
### Additional Context

Importantly this all worked without issue in version 0.49.2 of the helm template.

I am also able to exec into the pod running the spring boot service and telnet to the kubernetes default service and also the consul service running on port 8501.

**Comment by codex70** [comment] 2023-01-24 14:50
It looks like this could be related to https://github.com/hashicorp/consul/issues/15470, when I set transparent proxy to false, it works correctly. Having said that, I've updated the image to 1.14.3 and this makes no difference, so it may be something completely different. Anyway, with transparent proxy enabled, I get the above error when trying to use kubernetes configurations with spring cloud. This would seem to be a major issue as transparent proxy is required to run services correctly.

As a note, the SSLHandshakeException error when connecting to the consul server can be fixed by using `consul.service.consul` as the host instead of `host: "${HOST_IP}"`. I suspect this may be related to not running clients with connect inject.

**Comment by blake** [comment] 2023-01-25 18:01
@codex70 Excluding outbound port 443 from redirection will make it so that connections to _any_ IP – internal or external to your network – over port 443 will bypass the proxy. This is not ideal from a security perspective because it would allow applications to connect to arbitrary external destinations, and that traffic would not be subject to the security controls of the mesh.

A better solution would be to use the [`consul.hashicorp.com/transparent-proxy-exclude-outbound-cidrs`](https://developer.hashicorp.com/consul/docs/k8s/annotations-and-labels#consul-hashicorp-com-transparent-proxy-exclude-outbound-cidrs) annotation to only exempt traffic to the Kubernetes API server. For example:

```shell
$ kubectl get svc kubernetes --output jsonpath='{.spec.clusterIP}'
192.0.2.10
```

```yaml
# Pod spec
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  annotations:
    consul.hashicorp.com/transparent-proxy-exclude-outbound-cidrs: "192.0.2.10/32"
```

This would allow the application to communicate directly to the Kubernetes API when transparent proxy is enabled, while also avoiding exempting traffic to unintended destinations.

**Comment by codex70** [comment] 2023-01-26 14:24
@blake, thank you for that suggestion, makes perfect sense and I can limit it to an individual IP as you suggest.

I am interested to know if this is expected behaviour and whether it's likely to cause other problems that I'm not aware of.

**Comment by david-yu** [comment] 2023-01-26 17:24
@codex70 This is expected behavior of Transparent Proxy since Transparent Proxy is designed to intercept and redirect traffic through the proxy and not allow applications to dial arbitrary destinations. See more here: https://developer.hashicorp.com/consul/docs/connect/transparent-proxy. I'm not sure of what version of Consul you were using prior but we did default to enable TProxy when Consul 1.10.x was released with the Helm chart.

**Comment by codex70** [comment] 2023-01-26 17:44
Thanks @david-yu, I have been reading through the documentation, it's not clear to me how it would be possible to connect to a service that is outside of the service mesh without excluding specific ports or cidr blocks.

If I want to connect from a service mesh service to a service completely outside the service mesh (for example a REST API supplied by a third party), how would this be achieved. I'm unlikely to have a specific CIDR block, and probably wouldn't want to open up port (for example port 80). I'm sure this is just a misunderstanding on my part, but it's definitely a use case we would have.

**Comment by blake** [comment] 2023-01-26 19:06
@codex70 External services can be made available to the mesh through [terminating gateways](https://developer.hashicorp.com/consul/docs/connect/gateways/terminating-gateway).

The tutorial [Understand Terminating Gateways](https://developer.hashicorp.com/consul/tutorials/developer-mesh/service-mesh-terminating-gateways) details several traffic routing scenarios that can be achieved with terminating gateways. The [Connect External Services to Consul With Terminating Gateways](https://developer.hashicorp.com/consul/tutorials/developer-mesh/terminating-gateways-connect-external-services) tutorial walks through the process of registering an external service to Consul's catalog, and making it available in the mesh through the gateway.

As of Consul 1.13, you can skip the process of registering the service into the Consul catalog by using the new [Destinations](https://developer.hashicorp.com/consul/docs/connect/config-entries/service-defaults#terminating-gateway-destination) field in the service defaults configuration entry.

**Comment by david-yu** [comment] 2023-06-16 23:10
Closing as this is working as designed.

**Closed by david-yu** 2023-06-16 23:10 UTC
Labels: type/bug
