### ISSUE TITLE
OOM consul and consul-k8 (consul-k8 0.16.0)

### ISSUE THREAD

**Issue by fredstanley** [hashicorp/consul-k8s#294] opened 2020-07-13 21:42 UTC
I hit this issue  #283 and hence was using this private build
lkysow/consul-k8s-dev:jul07-resource-settings

Now in some cases i see consul hitting oom issue. My hunch is now the lifecycle container is hitting the resource limits.
can you pls increase the limit or remote the limit and just keep the request ?

const (
lifecycleContainerCPULimit = "20m"
lifecycleContainerCPURequest = "20m"
lifecycleContainerMemoryLimit = "25Mi"
lifecycleContainerMemoryRequest = "25Mi"
)

Appreciate if you can give a private fix

[66666.794649] RSP: 002b:00007fff487b8e50 EFLAGS: 00010202
[66666.794652] RAX: 000000c0001f8c00 RBX: 00007ff6138e3000 RCX: 000000c00088c000
[66666.794654] RDX: 000000c0001f8c00 RSI: 0000000006000446 RDI: 0000800000000000
[66666.794656] RBP: 00007fff487b8e80 R08: 000000c00088c000 R09: 0000000000000004
[66666.794657] R10: 00007ff6135f3bd8 R11: 0000000000000449 R12: 0000000000000003
[66666.794659] R13: 0000000000000000 R14: 000000000375e6d4 R15: 0000000000000000
[66666.794689] memory: usage 25600kB, limit 25600kB, failcnt 3986
[66666.794691] memory+swap: usage 0kB, limit 9007199254740988kB, failcnt 0
[66666.794692] kmem: usage 8792kB, limit 9007199254740988kB, failcnt 0
[66666.794693] Memory cgroup stats for /kubepods/burstable/pod04e7f3b6-de44-476f-a139-1e2ac473c5bf/0cf41faa207b73839cb76d608582691a29b4f5de7d4148f8242891bbcb9703a2:
[66666.794718] anon 16138240
file 0
kernel_stack 294912
slab 5472256
sock 0
shmem 0
file_mapped 0
file_dirty 0
file_writeback 0
anon_thp 0
inactive_anon 405504
active_anon 16084992
inactive_file 0
active_file 0
unevictable 135168
slab_reclaimable 434176
slab_unreclaimable 5038080
pgfault 728640
pgmajfault 0
workingset_refault 0
workingset_activate 0
workingset_nodereclaim 0
pgrefill 0
pgscan 9532
pgsteal 2009
pgactivate 3498
pgdeactivate 0
pglazyfree 25575
pglazyfreed 1947
thp_fault_alloc 0
thp_collapse_alloc 0
[66666.794720] Tasks state (memory values in pages):
[66666.794722] [ pid ] uid tgid total_vm rss pgtables_bytes swapents oom_score_adj name
[66666.794730] [2998520] 100 2998520 190368 7650 200704 0 999 consul-k8s
[66666.794736] [3351864] 100 3351864 196558 13132 266240 0 999 consul
[66666.794738] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=0cf41faa207b73839cb76d608582691a29b4f5de7d4148f8242891bbcb9703a2,mems_allowed=0-1,oom_memcg=/kubepods/burstable/pod04e7f3b6-de44-476f-a139-1e2ac473c5bf/0cf41faa207b73839cb76d608582691a29b4f5de7d4148f8242891bbcb9703a2,task_memcg=/kubepods/burstable/pod04e7f3b6-de44-476f-a139-1e2ac473c5bf/0cf41faa207b73839cb76d608582691a29b4f5de7d4148f8242891bbcb9703a2,task=consul,pid=3351864,uid=100
[66666.794823] Memory cgroup out of memory: Killed process 3351864 (consul) total-vm:786232kB, anon-rss:11028kB, file-rss:41660kB, shmem-rss:0kB, UID:100 pgtables:260kB oom_score_adj:999
[66666.811642] oom_reaper: reaped process 3351864 (consul), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

**Comment by adilyse** [comment] 2020-07-14 18:04
Hi @fredstanley,

Here's a build that increases the lifecycle sidecar memory limit to 40Mi: `lkysow/consul-k8s-dev:jul14-lifecycle-sidecar-resource`

Could you also share some details about your setup? We haven't been able to reproduce the memory issues you're running into so any information you could provide would be helpful. Specifically:

- What version of Kubernetes are you running?
- Are you running on a managed version, bare metal, or on a test environment locally?
- What size are the nodes and how many?
- Are there any resource restrictions in place? Are resource limits required?
- Are there a lot of things deployed that are competing for resources?

**Comment by nasuku** [comment] 2020-07-14 23:31
Hello @adilyse  - about this issue on @fredstanley setup :

Answers to your questions below:
====
we have seen this both on AWS EKS container (running on EC2) as well as baremetal VM.

AWS was running:
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-fd1ea7", GitCommit:"fd1ea7c64d0e3ccbf04b124431c659f65330562a", GitTreeState:"clean", BuildDate:"2020-05-28T19:06:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Our baremetal was running:
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

We had lots of free memory on the nodes.
AWS has multiple nodes and baremetal was a single node.

No other resource limits.

The resource usage was also very less.
====

**Comment by nasuku** [comment] 2020-07-14 23:36
Few more observations:

The OOM kills were not seen on any k8s logs. But were observed with the dmesg on the linux node.
Preliminary analysis:
there is a sidecar with the following command running:
 consul-k8s lifecycle-sidecar -service-config /consul/connect-inject/service.hcl -consul-binary /consul/connect-inject/consul

It looks like evert 20 seconds or so, the consul-k8s binary runs a command:
/consul/connect-inject/consul services register /consul/connect-inject/service.hcl

The total memory limit for this POD was 25Mi.
However the child process (consul services register ..) when it runs seems to take up memory where the total  for both the processes is more than 25Mi. (Since its always the child process which takes more memory, it gets killed by the linux oom killer).

Since the main process continues to run, we dont see any container restart or anything like that and hence both docker and kubelet are unaware of this child process death.

**Comment by adilyse** [comment] 2020-07-15 18:02
Hi @nasuku,

That's super helpful information! It gives us a number of places to start looking.

For the memory usage that eventually results in OOM, what does it look like over time? Does it gradually increase? Does it spike at certain points?

**Comment by nasuku** [comment] 2020-07-16 02:43
The node has lots of free memory. In all the instances that we observed, the memory limit was hit only when the subprocess was also running (which seems to run every 21 seconds or so). Its not that the crash happens every time.

**Comment by adilyse** [comment] 2020-07-31 18:24
We've released [`consul-k8s v0.18.0`](https://github.com/hashicorp/consul-k8s/blob/master/CHANGELOG.md#0180-july-30-2020) and [`consul-helm v0.24.0`](https://github.com/hashicorp/consul-helm/blob/master/CHANGELOG.md#0240-july-31-2020) that make these settings configurable to address this issue, as well as bumping the lifecycle sidecar memory limit default to `50Mi`.

We're still investigating whether there's a larger underlying issue, but this should unblock folks while we figure that out. The future investigation will be tracked on #295, so I'll go ahead and close this. Thank you for all of the detailed information!

**Closed by adilyse** 2020-07-31 18:24 UTC
Labels: area/connect, bug
