### ISSUE TITLE
helm:Envoy sidecar shutting down too early causes requests to fail

### ISSUE THREAD

**Issue by nflaig** [hashicorp/consul-k8s#650] opened 2021-03-17 21:00 UTC
Hey guys,

during a rolling update (pod termination) we are getting 502 errors in nginx for upstream requests. This happens because the load balancer in k8s still sends requests to the terminating pod due to the fact that the endpoint deregistration happens asynchronously, see https://github.com/kubernetes/kubernetes/issues/43576.

For nginx itself, I was able to resolve this race condition issue by adding a simple sleep to the `preStop` hook of the container
```
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "sleep 5 && /usr/sbin/nginx -s quit"]
```

but the problem is not fully resolved since the envoy sidecar is still shutting down too early which causes requests to fail.

### Current behavior

Nginx returns 502 errors because the upstream requests are send through the envoy sidecar proxy which is already shutting down due to the `SIGTERM` send by k8s.

### Expected behavior 

The envoy sidecar proxy should handle requests of the proxied service as long as the service is still running, e.g. if the service does some cleanup and still needs to send data when terminating or in case of nginx if further requests are still being routed to the pod.

### Suggestion

In the [envoy preStop command](https://github.com/hashicorp/consul-k8s/blob/master/connect-inject/envoy_sidecar.go#L194) a delay could be added to prevent instantly sending the `SIGTERM` signal to the container. Since a hardcoded sleep duration seems to  be too static maybe it would make sense to add something like this 
```
while [ $(netstat -plunt | grep tcp | grep -v envoy | wc -l | xargs) -ne 0 ]; do sleep 1; done
```
It would delay the shutdown process of envoy until there are no more TCP listeners, i.e. the proxied service is no longer running and it is save to also shutdown envoy without causing further requests to fail.

Another option could be to allow the user of the helm chart to customize the envoy `preStop` hook.

### Environment details

- `consul-k8s` version: 0.24.0
- `consul-helm` version: 0.30.0
- `consul` version: 1.9.3
- `envoy` version: 1.16.0

### Related

- https://github.com/istio/istio/issues/7136
- https://github.com/istio/istio/issues/10112
- https://github.com/istio/istio/issues/7665
- https://github.com/istio/istio/issues/12183
- https://github.com/istio/istio/pull/11298
- https://github.com/istio/istio/pull/12342
- [HashiCorp Forum Post](https://discuss.hashicorp.com/t/delay-sigterm-of-envoy-sidecar-proxy/22036)

**Comment by Samjin** [comment] 2021-11-01 15:50
hi @nflaig doesn't **terminationDrainDuration** solve the problem or I'm missing anything?

**Comment by nflaig** [comment] 2021-11-01 18:15
Hi @Samjin, it does not solve the problem as it still prevents new connections

**Comment by ryan4yin** [comment] 2021-11-16 16:22
@Samjin only `preStop` can delay sending SIGTERM signals to Envoy.
without `preStop`, Envoy will receive the SIGTERM signal immediately, and reject all the new connections.

**Comment by Samjin** [comment] 2021-11-17 20:43
@ryan4yin Let me know if I understand this correctly. While the pod ip is being removed from iptable, istio-proxy and your service have already received SIGTERM and stopped accepting any new request, this is causing problem because requests are still coming in through the available Pod IP. 
If my understanding is correct, wouldn't just add `preStop` in both service and istio-proxy containers work so  they can still accept request until pod IP is removed?

**Comment by ryan4yin** [comment] 2021-11-18 03:30
@Samjin Correct, that's what we're doing right now.

**Comment by hamishforbes** [comment] 2021-12-08 02:59
I'm seeing a similar issue but using the [AWS ALB Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller)
My app receives public HTTP requests via an ALB and forwards them on to other services via Consul Connect.

We also make extensive use of long polling so often have HTTP requests that take 27s to return.
I have set a [deregistration delay](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#deregistration-delay) and a `preStop` that sleeps for 30s to allow these requests to complete.

There's also a small lag between a pod being marked as terminating and the ALB being fully updated to not send new requests to the pod.

At the moment though the pod is marked terminating, preStop fires on my container and the envoy sidecar immediately shuts down.
Some requests sneak through before the ALB updates, my app tries to forward these on and finds the envoy sidecar listeners are closed, and so returns an error.

Being able to set a preStop on the envoy container as well would resolve this problem entirely.

**Comment by bmihaescu** [comment] 2022-03-07 14:43
> I'm seeing a similar issue but using the [AWS ALB Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) My app receives public HTTP requests via an ALB and forwards them on to other services via Consul Connect.

@hamishforbes, what did you configure on the alb ingress controller side to make it work with consul connect? I'm not able to send requests to a service that's under consul connect, by accessing it through ALB.

**Comment by stk0vrfl0w** [comment] 2022-03-17 19:15
We're seeing similar issues with release `0.41.1`.

In our case, the `mesh-gateway` container's probes fail while the envoy proxy is still initializing.  We suspect that the long initialization times may be due to the number of federated clusters we have connected -- just over a dozen and counting.  Fortunately, we've been able to work around this by manually tweaking the deployment's probes' parameters.

As we're using `helmfile` and `kustomize` internally, our deployment pipeline can dynamically patch the charts, though it would be beneficial to all if the probes' settings were parameterized in `values.yaml` and if a `startupProbe` stanza was added.

**Comment by narendrapatel** [comment] 2022-08-05 11:23
We have a similar issue where our app container has draining configured. As such on termination it starts draining the requests with a max time f.e say 3 minutes. But since the sidecar has no corresponding config it shuts down immediately. The problem is that when during this period the draining requests makes a connection to the sidecar they receive "connection refused" error as the sidecar is already stopped, resulting in failures and noise in logs.

**Comment by david-yu** [comment] 2023-06-28 03:12
Closing as the pod shutdown use case of sidecar lifecycle should now be addressed by https://github.com/hashicorp/consul-k8s/pull/2233. Please open a new issue if you still have issues.

**Closed by david-yu** 2023-06-28 03:12 UTC
