### ISSUE TITLE
[Question] local dev environment instructions

### ISSUE THREAD

**Issue by ltagliamonte-dd** [hashicorp/consul-k8s#327] opened 2020-09-21 23:37 UTC
I'm having issue in running this code in debug on my mac.
I'm using visual studio and the following launch.json config:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "Users/luigi.tagliamonte/go/src/github.com/hashicorp/consul-k8s",
            "env": {
                "CONSUL_HTTP_ADDR":"127.0.0.1:8500",
            },
            "args": [
                "sync-catalog",
                "-log-level=debug",
            ]
        }
    ]
}
```

I'm running consul in container using:
```
docker run -it -p 8500:8500 --name=dev-consul --rm -e CONSUL_BIND_INTERFACE=eth0 consul
```
and I have a local k8s cluster as well.

The app starts but it exit on:
```
Failed to continue - runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation]
Unable to propogate EXC_BAD_ACCESS signal to target process and panic (see https://github.com/go-delve/delve/issues/852)
Last known immediate stacktrace (goroutine id 0):
```

Full logs:
```
API server listening at: 127.0.0.1:25134
2020-09-21T16:32:08.209-0700 [INFO]  K8s namespace syncing configuration: k8s namespaces allowed to be synced=Set{} k8s namespaces denied from syncing=Set{}
Listening on ":8080"...
2020-09-21T16:32:08.209-0700 [INFO]  to-consul/source: starting runner for endpoints
2020-09-21T16:32:08.209-0700 [INFO]  to-k8s/sink: starting runner for syncing
2020-09-21T16:32:08.416-0700 [INFO]  to-k8s/source: received services from Consul: count=1
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/source.controller/endpoints: queue: op=add key=default/kubernetes
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/source.controller/endpoints: queue: op=add key=kube-system/kube-controller-manager

2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/controller: queue: op=add key=kube-system/tiller-deploy
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/controller: queue: op=add key=test-ns/python-headless-service
2020-09-21T16:32:08.430-0700 [DEBUG] to-k8s/controller: queue: op=add key=default/consul
2020-09-21T16:32:08.430-0700 [DEBUG] to-k8s/controller: queue: op=add key=default/kubernetes
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/source.controller/endpoints: queue: op=add key=kube-system/kube-dns
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/source.controller/endpoints: queue: op=add key=test-ns/python-headless-service
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/controller: queue: op=add key=default/consul
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/source.controller/endpoints: queue: op=add key=argo-rollouts/argo-rollouts-metrics
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/source.controller/endpoints: queue: op=add key=docker/compose-api
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/source.controller/endpoints: queue: op=add key=kube-system/docker.io-hostpath
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/source.controller/endpoints: queue: op=add key=kube-system/kube-scheduler
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/controller: queue: op=add key=argo-rollouts/argo-rollouts-metrics
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/source.controller/endpoints: queue: op=add key=kube-system/tiller-deploy
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/controller: queue: op=add key=default/kubernetes
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/controller: queue: op=add key=docker/compose-api
2020-09-21T16:32:08.430-0700 [DEBUG] to-consul/controller: queue: op=add key=kube-system/kube-dns
2020-09-21T16:32:08.443-0700 [INFO]  to-consul/source.controller/endpoints: initial cache sync complete
2020-09-21T16:32:08.449-0700 [DEBUG] to-consul/source.controller/endpoints: processing object: key=default/kubernetes exists=true
2020-09-21T16:32:08.457-0700 [DEBUG] to-consul/source.controller/endpoints: processing object: key=kube-system/kube-controller-manager exists=true
2020-09-21T16:32:08.459-0700 [DEBUG] to-consul/source.controller/endpoints: processing object: key=kube-system/kube-dns exists=true
2020-09-21T16:32:08.481-0700 [DEBUG] to-consul/source.controller/endpoints: processing object: key=test-ns/python-headless-service exists=true
2020-09-21T16:32:08.490-0700 [DEBUG] to-consul/source.controller/endpoints: processing object: key=argo-rollouts/argo-rollouts-metrics exists=true
2020-09-21T16:32:08.502-0700 [DEBUG] to-consul/source.controller/endpoints: processing object: key=docker/compose-api exists=true
2020-09-21T16:32:08.518-0700 [DEBUG] to-consul/source.controller/endpoints: processing object: key=kube-system/docker.io-hostpath exists=true
2020-09-21T16:32:08.545-0700 [DEBUG] to-consul/source.controller/endpoints: processing object: key=kube-system/kube-scheduler exists=true
2020-09-21T16:32:08.542-0700 [INFO]  to-consul/controller: initial cache sync complete
2020-09-21T16:32:08.542-0700 [INFO]  to-k8s/controller: initial cache sync complete
2020-09-21T16:32:08.564-0700 [DEBUG] to-consul/source.controller/endpoints: processing object: key=kube-system/tiller-deploy exists=true
2020-09-21T16:32:08.568-0700 [DEBUG] to-consul/controller: processing object: key=kube-system/tiller-deploy exists=true
2020-09-21T16:32:08.571-0700 [DEBUG] to-k8s/controller: processing object: key=default/consul exists=true
Failed to continue - runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation]
Unable to propogate EXC_BAD_ACCESS signal to target process and panic (see https://github.com/go-delve/delve/issues/852)
Last known immediate stacktrace (goroutine id 0):
```

Is there any setup documentation?
Thanks.

**Comment by lkysow** [comment] 2020-09-28 19:03
Hi, I can't reproduce that error but I'm not using visual studio. Is visual studio compiling and running with the debugger (delve)? From the error messages it appears that it is. I think the panic is due to the interaction between delve and consul-k8s.

If you run `go install` and then run `consul-k8s sync-catalog` do you see the panic?

**Comment by ltagliamonte-dd** [comment] 2020-09-28 21:34
Thank you for the followup on this, yes i'm using delve, go install works with no panics

**Comment by lkysow** [comment] 2020-09-29 02:52
So from the error message this looks like a bug with delve https://github.com/go-delve/delve/issues/852

**Comment by ltagliamonte-dd** [comment] 2020-09-29 03:05
Yeah I saw that, is anyone of you at hashicorp running this on osx? I suppose yes...

**Comment by lkysow** [comment] 2020-09-29 20:34
Yep. I use goland's debugger though and I haven't had any issues.

**Comment by lkysow** [comment] 2020-12-01 02:56
Hi Luigi, we're going to close this one because I'm not sure there's anything we can do. But we're happy to re-open if that's incorrect.

**Closed by lkysow** 2020-12-01 02:56 UTC
Labels: question, waiting-on-response
