### ISSUE TITLE
rpc error on sync & inject pod initializations while upgrading to 1.1.0

### ISSUE THREAD

**Issue by satishkandi** [hashicorp/consul-k8s#2033] opened 2023-03-29 16:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

We upgraded the server cluster(external) to 1.15.0 and trying to upgrade consul-k8s to 1.1.0. 

Communications breakdown with this message(consul sync log) :
connection error: error="fetching supported dataplane features: rpc error: code = Unauthenticated desc = An ACL token must be provided (via the `x-consul-token` metadata field) to call this endpoint"

### Reproduction Steps

Values.yaml snippets:

    tls:
      caCert:
        secretKey: ca_file
        secretName: consul-agent-ca-cert
      serverAdditionalDNSSANs: ["localhost", "server.dc0.consul"]
      enabled: true
      httpsOnly: true
      verify: false
    aclSyncToken:
        secretKey: CONSUL_HTTP_TOKEN
        secretName: consultoken     
  externalServers:
    enabled: true
    hosts:
      - consul01
      - consul02
      - consul03
      - consul04
    grpcPort: 8503
    tlsServerName: server.dc0.consul
  server:
    enabled: false

  syncCatalog:
    enabled: true
    image: null
    default: true
    aclSyncToken:
      secretName: consultoken
      secretKey: CONSUL_HTTP_TOKEN
    consulPrefix: pf-
    k8sTag: pf
    logLevel: debug

### Logs

Log from the service sync pod:

2023-03-28T15:51:32.900Z [INFO]  consul-server-connection-manager: trying to connect to a Consul server
2023-03-28T15:51:32.900Z [TRACE] consul-server-connection-manager: Watcher.nextServer: addrs=[]
2023-03-28T15:51:33.099Z [DEBUG] consul-server-connection-manager: Resolved DNS name: name=ss25consul01.dc025.sf.priv ip-addrs=["{10.181.0.25 }"]
2023-03-28T15:51:33.099Z [INFO]  consul-server-connection-manager: discovered Consul servers: addresses=[10.181.0.25:8503]
2023-03-28T15:51:33.099Z [INFO]  consul-server-connection-manager: current prioritized list of known Consul servers: addresses=[10.181.0.25:8503]
2023-03-28T15:51:33.099Z [TRACE] consul-server-connection-manager: Watcher.connect: addr=10.181.0.25:8503
2023-03-28T15:51:33.099Z [DEBUG] consul-server-connection-manager: switching to Consul server: address=10.181.0.25:8503
2023-03-28T15:51:33.099Z [TRACE] consul-server-connection-manager: Watcher.switchServer: to=10.181.0.25:8503
2023-03-28T15:51:33.100Z [TRACE] consul-server-connection-manager: balancerBuilder.Build
2023-03-28T15:51:33.100Z [TRACE] consul-server-connection-manager: clientConnWrapper.NewSubConn: addrs=["{\n  \"Addr\": \"10.181.0.25:8503\",\n  \"ServerName\": \"\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}"]
2023-03-28T15:51:33.100Z [TRACE] consul-server-connection-manager: pickerBuilder.Build: sub-conns ready=0
2023-03-28T15:51:33.100Z [TRACE] consul-server-connection-manager: balancer.UpdateSubConnState: sc="&{{0 0} 0xc00077e000}" state="{CONNECTING <nil>}"
2023-03-28T15:51:33.306Z [TRACE] consul-server-connection-manager: balancer.UpdateSubConnState: sc="&{{0 0} 0xc00077e000}" state="{READY <nil>}"
2023-03-28T15:51:33.306Z [TRACE] consul-server-connection-manager: pickerBuilder.Build: sub-conns ready=1
2023-03-28T15:51:33.500Z [DEBUG] consul-server-connection-manager: switched to Consul server successfully: address=10.181.0.25:8503
2023-03-28T15:51:33.502Z [TRACE] consul-server-connection-manager: balancer.UpdateSubConnState: sc="&{{0 0} 0xc00077e000}" state="{SHUTDOWN <nil>}"
2023-03-28T15:51:33.502Z [DEBUG] consul-server-connection-manager: gRPC resolver failed to update connection address: error="bad resolver state"
2023-03-28T15:51:33.502Z [ERROR] consul-server-connection-manager: connection error: error="fetching supported dataplane features: rpc error: code = Unauthenticated desc = An ACL token must be provided (via the `x-consul-token` metadata field) to call this endpoint"
2023-03-28T15:51:33.502Z [DEBUG] consul-server-connection-manager: backoff: retry after=540.46576ms

Log from the injector pod:

2023-03-29T14:00:27.988Z [INFO]  consul-server-connection-manager: trying to connect to a Consul server
2023-03-29T14:00:27.988Z [TRACE] consul-server-connection-manager: Watcher.nextServer: addrs=[]
2023-03-29T14:00:28.188Z [DEBUG] consul-server-connection-manager: Resolved DNS name: name=xxxx.xx.xx ip-addrs=["{10.181.0.25 }"]
2023-03-29T14:00:28.188Z [INFO]  consul-server-connection-manager: discovered Consul servers: addresses=[10.181.0.25:8503]
2023-03-29T14:00:28.188Z [INFO]  consul-server-connection-manager: current prioritized list of known Consul servers: addresses=[10.181.0.25:8503]
2023-03-29T14:00:28.188Z [TRACE] consul-server-connection-manager: Watcher.connect: addr=10.181.0.25:8503
2023-03-29T14:00:28.188Z [DEBUG] consul-server-connection-manager: switching to Consul server: address=10.181.0.25:8503
2023-03-29T14:00:28.188Z [TRACE] consul-server-connection-manager: Watcher.switchServer: to=10.181.0.25:8503
2023-03-29T14:00:28.188Z [TRACE] consul-server-connection-manager: balancerBuilder.Build
2023-03-29T14:00:28.188Z [TRACE] consul-server-connection-manager: clientConnWrapper.NewSubConn: addrs=["{\n  \"Addr\": \"10.181.0.25:8503\",\n  \"ServerName\": \"\",\n  \"Attributes\": null,\n  \"BalancerAttributes\": null,\n  \"Type\": 0,\n  \"Metadata\": null\n}"]
2023-03-29T14:00:28.188Z [TRACE] consul-server-connection-manager: pickerBuilder.Build: sub-conns ready=0
2023-03-29T14:00:28.188Z [TRACE] consul-server-connection-manager: balancer.UpdateSubConnState: sc="&{{0 0} 0xc00014f340}" state="{CONNECTING <nil>}"
2023-03-29T14:00:28.282Z [TRACE] consul-server-connection-manager: balancer.UpdateSubConnState: sc="&{{0 0} 0xc00014f340}" state="{READY <nil>}"
2023-03-29T14:00:28.282Z [TRACE] consul-server-connection-manager: pickerBuilder.Build: sub-conns ready=1
2023-03-29T14:00:28.389Z [DEBUG] consul-server-connection-manager: switched to Consul server successfully: address=10.181.0.25:8503
2023-03-29T14:00:28.390Z [TRACE] consul-server-connection-manager: balancer.UpdateSubConnState: sc="&{{0 0} 0xc00014f340}" state="{SHUTDOWN <nil>}"
2023-03-29T14:00:28.391Z [DEBUG] consul-server-connection-manager: gRPC resolver failed to update connection address: error="bad resolver state"
2023-03-29T14:00:28.391Z [ERROR] consul-server-connection-manager: connection error: error="fetching supported dataplane features: rpc error: code = Unauthenticated desc = An ACL token must be provided (via the `x-consul-token` metadata field) to call this endpoint"
2023-03-29T14:00:28.391Z [DEBUG] consul-server-connection-manager: backoff: retry after=384.07708ms

### Environment details

k8s version : v1.24.10
consul-k8s-control-plane:1.1.0
consul:1.15.0

**Comment by komapa** [comment] 2023-05-17 17:18
The problem is that the PodSpec sets it as CONSUL_HTTP_TOKEN, when the sync executable expects it as `CONSUL_ACL_TOKEN`, so this is the bug.

**Comment by david-yu** [comment] 2023-05-17 22:00
Does this PR resolve your issue? https://github.com/hashicorp/consul-k8s/pull/2068. Consul K8s 1.1.2 should resolve this issue and will be released by end of the month.

**Comment by david-yu** [comment] 2023-06-16 21:11
Will close as its related to https://github.com/hashicorp/consul-k8s/pull/2068

**Closed by david-yu** 2023-06-16 21:11 UTC
Labels: type/bug

**Comment by danielmotaleite** [comment] 2023-09-06 20:35
to anyone arriving here, this image should fix this, next with the latest helm ( helm repo update hashicorp ):

```
syncCatalog:
  enabled: true
  image: hashicorp/consul-k8s-control-plane:1.2.1
```
