### ISSUE TITLE
Wrong CONSUL_HTTP_ADDR of consul-connect-inject-init

### ISSUE THREAD

**Issue by reidlai** [hashicorp/consul-k8s#302] opened 2020-07-31 06:03 UTC
I have already setup Consul Connect and it is working fine until i imlement inject-connect  annotation.  This is my error I encountered when I deploy etcd for Loki ring.  I know Consul has KV but Loki does not allow me to specify tlsConfig so I need to create etcd pure for loki cluster.

When I deployed etcd statefulset i got the following error.

kubectl logs --follow pod/etcd-0 -n gohub-core-minikube -c consul-connect-inject-init                 
Error logging in: Post "https://192.168.64.54:8501/v1/acl/login": x509: certificate is valid for 127.0.0.1, ::, not 192.168.64.54

Here IP 192.168.64.54 is my minikube ip which should not be accessed among PODs

After tracing consul-connect-inject-init, I found the injector use read etcd POD hostIp as CONSUL_HTTP_ADDR.  I am supposing CONSUL_HTTP_ADDR should point to Consul Server Kubernetes service DNS.  Is there any way i can override CONSUL_HTTP_ADDR and CONSUL_GRPC_ADDR in consul-connect-inject-init?

```
initContainers:
  - command:
    - /bin/sh
    - -ec
    - |2-

      export CONSUL_HTTP_ADDR="https://${HOST_IP}:8501"
      export CONSUL_GRPC_ADDR="https://${HOST_IP}:8502"
      export CONSUL_CACERT=/consul/connect-inject/consul-ca.pem
      cat <<EOF >/consul/connect-inject/consul-ca.pem
  ... 
      EOF

      # Register the service. The HCL is stored in the volume so that
      # the preStop hook can access it to deregister the service.
      cat <<EOF >/consul/connect-inject/service.hcl
      services {
        id   = "${PROXY_SERVICE_ID}"
        name = "etcd-sidecar-proxy"
        kind = "connect-proxy"
        address = "${POD_IP}"
        port = 20000
        meta = {
          pod-name = "${POD_NAME}"
        }

        proxy {
          destination_service_name = "etcd"
          destination_service_id = "${SERVICE_ID}"
          local_service_address = "127.0.0.1"
          local_service_port = 2379
        }

        checks {
          name = "Proxy Public Listener"
          tcp = "${POD_IP}:20000"
          interval = "10s"
          deregister_critical_service_after = "10m"
        }

        checks {
          name = "Destination Alias"
          alias_service = "${SERVICE_ID}"
        }
      }

      services {
        id   = "${SERVICE_ID}"
        name = "etcd"
        address = "${POD_IP}"
        port = 2379
        meta = {
          pod-name = "${POD_NAME}"
        }
      }
      EOF
      /bin/consul login -method="gohub-consul-cluster-consul-k8s-auth-method" \
        -bearer-token-file="/var/run/secrets/kubernetes.io/serviceaccount/token" \
        -token-sink-file="/consul/connect-inject/acl-token" \
        -meta="pod=${POD_NAMESPACE}/${POD_NAME}"
      chmod 444 /consul/connect-inject/acl-token

      /bin/consul services register \
        -token-file="/consul/connect-inject/acl-token" \
        /consul/connect-inject/service.hcl

      # Generate the envoy bootstrap code
      /bin/consul connect envoy \
        -proxy-id="${PROXY_SERVICE_ID}" \
        -token-file="/consul/connect-inject/acl-token" \
        -bootstrap > /consul/connect-inject/envoy-bootstrap.yaml

      # Copy the Consul binary
      cp /bin/consul /consul/connect-inject/consul
    env:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: SERVICE_ID
      value: $(POD_NAME)-etcd
    - name: PROXY_SERVICE_ID
      value: $(POD_NAME)-etcd-sidecar-proxy
```

**Comment by kschoche** [comment] 2020-07-31 15:32
Hi @reidlai thanks for filing this bug! Would you be able to provide a bit more information on your deployment? I'd like to try to reproduce it on my end as well.

A copy of the custom values file you used to deploy with helm, along with your etcd deployment yaml would be helpful in identifying any underlying issues.

Much of Consuls communication is through localhost to the Agent running as a daemon set on each node which is why hostIP is being referenced in a few places but it is possible something is misconfigured here as well.

**Comment by lkysow** [comment] 2020-08-06 17:33
Just to be clear, regarding:

> CONSUL_HTTP_ADDR should point to Consul Server Kubernetes service DNS

CONSUL_HTTP_ADDR should point to the IP address of the Consul client pod running on the same node as the connect injector.

**Comment by lkysow** [comment] 2020-09-02 22:47
Hi, we're going to close this because we haven't head back but we can re-open if needed.

**Closed by lkysow** 2020-09-02 22:47 UTC
Labels: area/connect, waiting-on-response
