### ISSUE TITLE
consul-connect-inject-init: "unable to find registered connect-proxy service"

### ISSUE THREAD

**Issue by pankaj-dahiya** [hashicorp/consul-k8s#764] opened 2021-10-06 18:46 UTC
**Overview of the Issue:**

I am trying to use Consul service mesh (connect).

I am using a freshly deployed k8s cluster, a new consul-helm deployment and I try to deploy any other service with service mesh integration.
The consul-connect-inject-init container fails and crash loops, so the pod never completes the init phase.

**Reproduction Steps**
helm install consul hashicorp/consul --set connectInject.enabled=true --set connectInject.default=true.

Once consul is running, deploy any service. In my case a simple keycloak with postgresql manifest, but I have tried others with the same behaviour.

ubuntu@ip-172-31-37-34:~/pankaj$ kubectl get po
NAME                                                              READY   STATUS     RESTARTS   AGE
pankaj-consul-server-1                                            0/1     Pending    0          15m
pankaj-consul-server-2                                            0/1     Pending    0          15m
pankaj-consul-kstjl                                               0/1     Running    0          15m
pankaj-consul-webhook-cert-manager-5f5d9cf784-wjh5x               1/1     Running    0          15m
pankaj-consul-controller-67968c745-hs24s                          1/1     Running    0          15m
pankaj-consul-connect-injector-webhook-deployment-5868b8d6mm5z4   1/1     Running    0          15m
pankaj-consul-connect-injector-webhook-deployment-5868b8d67qzvr   1/1     Running    0          15m
pankaj-keycloak-0                                                 0/2     Init:0/3   0          15m
pankaj-consul-server-0                                            0/1     Running    0          15m
pankaj-postgresql-0                                               0/2     Init:1/2   5          15m

ubuntu@ip-172-31-37-34:~/pankaj$ kubectl logs pankaj-postgresql-0 consul-connect-inject-init
2021-10-06T18:43:53.093Z [INFO]  Registered service has been detected: service=pankaj-postgresql-headless
2021-10-06T18:43:54.095Z [INFO]  Registered service has been detected: service=pankaj-postgresql
2021-10-06T18:43:54.095Z [INFO]  Registered service has been detected: service=pankaj-postgresql-headless
2021-10-06T18:43:55.096Z [INFO]  Registered service has been detected: service=pankaj-postgresql
2021-10-06T18:43:55.096Z [INFO]  Registered service has been detected: service=pankaj-postgresql-headless
2021-10-06T18:43:56.097Z [INFO]  Registered service has been detected: service=pankaj-postgresql
2021-10-06T18:43:56.097Z [INFO]  Registered service has been detected: service=pankaj-postgresql-headless
2021-10-06T18:43:56.097Z [ERROR] Timed out waiting for service registration: error="unable to find registered connect-proxy service"

**Comment by lkysow** [comment] 2021-10-06 18:49
Can you show `kubectl describe pod pankaj-consul-server-1`. Both those server pods need to be running before anything will work.

If you're just doing testing then you can use a single server:

```
server:
  replicas: 1
```

**Comment by pankaj-dahiya** [comment] 2021-10-06 18:50
ubuntu@ip-172-31-37-34:~/pankaj$ kubectl describe pod pankaj-consul-server-1
Name:           pankaj-consul-server-1
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=consul
                chart=consul-helm
                component=server
                controller-revision-hash=pankaj-consul-server-59f47fbcd6
                hasDNS=true
                release=pankaj
                statefulset.kubernetes.io/pod-name=pankaj-consul-server-1
Annotations:    consul.hashicorp.com/config-checksum: 914926d24d7bf77220ba40bb3625bc3103f9ddceb7042745eb0454d507be5706
                consul.hashicorp.com/connect-inject: false
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/pankaj-consul-server
Containers:
  consul:
    Image:       hashicorp/consul:1.10.2
    Ports:       8500/TCP, 8301/TCP, 8301/UDP, 8302/TCP, 8302/UDP, 8300/TCP, 8600/TCP, 8600/UDP
    Host Ports:  0/TCP, 0/TCP, 0/UDP, 0/TCP, 0/UDP, 0/TCP, 0/TCP, 0/UDP
    Command:
      /bin/sh
      -ec
      CONSUL_FULLNAME="pankaj-consul"
      
      mkdir -p /consul/extra-config
      cp /consul/config/extra-from-values.json /consul/extra-config/extra-from-values.json
      [ -n "${HOST_IP}" ] && sed -Ei "s|HOST_IP|${HOST_IP?}|g" /consul/extra-config/extra-from-values.json
      [ -n "${POD_IP}" ] && sed -Ei "s|POD_IP|${POD_IP?}|g" /consul/extra-config/extra-from-values.json
      [ -n "${HOSTNAME}" ] && sed -Ei "s|HOSTNAME|${HOSTNAME?}|g" /consul/extra-config/extra-from-values.json
      
      exec /usr/local/bin/docker-entrypoint.sh consul agent \
        -advertise="${ADVERTISE_IP}" \
        -bind=0.0.0.0 \
        -bootstrap-expect=3 \
        -client=0.0.0.0 \
        -config-dir=/consul/config \
        -datacenter=dc1 \
        -data-dir=/consul/data \
        -domain=consul \
        -hcl="connect { enabled = true }" \
        -ui \
        -retry-join="${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
        -retry-join="${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
        -retry-join="${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
        -serf-lan-port=8301 \
        -config-file=/consul/extra-config/extra-from-values.json \
        -server
      
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:      100m
      memory:   100Mi
    Readiness:  exec [/bin/sh -ec curl http://127.0.0.1:8500/v1/status/leader \
2>/dev/null | grep -E '".+"'
] delay=5s timeout=5s period=3s #success=1 #failure=2
    Environment:
      ADVERTISE_IP:               (v1:status.podIP)
      HOST_IP:                    (v1:status.hostIP)
      POD_IP:                     (v1:status.podIP)
      NAMESPACE:                 default (v1:metadata.namespace)
      CONSUL_DISABLE_PERM_MGMT:  true
    Mounts:
      /consul/config from config (rw)
      /consul/data from data-default (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ppd2q (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data-default:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-default-pankaj-consul-server-1
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      pankaj-consul-server-config
    Optional:  false
  kube-api-access-ppd2q:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  20m   default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity rules, 1 node(s) didn't match pod anti-affinity rules.
  Warning  FailedScheduling  20m   default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity rules, 1 node(s) didn't match pod anti-affinity rules.

**Comment by lkysow** [comment] 2021-10-06 18:52
I think you don't have enough nodes in your cluster. See my previous comment if it's a test cluster.

**Comment by pankaj-dahiya** [comment] 2021-10-06 18:55
`ubuntu@ip-172-31-37-34:~/pankaj$ kubectl get po
NAME                                                              READY   STATUS                  RESTARTS   AGE
pankaj-consul-webhook-cert-manager-5f5d9cf784-wjh5x               1/1     Running                 0          25m
pankaj-consul-controller-67968c745-hs24s                          1/1     Running                 0          25m
pankaj-consul-connect-injector-webhook-deployment-5868b8d6mm5z4   1/1     Running                 0          25m
pankaj-keycloak-0                                                 0/2     Init:0/3                0          24m
pankaj-postgresql-0                                               0/2     Init:CrashLoopBackOff   6          24m
pankaj-consul-server-0                                            1/1     Running                 0          32s
pankaj-consul-drsqz                                               1/1     Running                 0          22s


ubuntu@ip-172-31-37-34:~/pankaj$ kubectl describe pod pankaj-consul-server-0
Name:         pankaj-consul-server-0
Namespace:    default
Priority:     0
Node:         ip-172-31-37-34/172.31.37.34
Start Time:   Wed, 06 Oct 2021 18:54:21 +0000
Labels:       app=consul
              chart=consul-helm
              component=server
              controller-revision-hash=pankaj-consul-server-54f4d9d687
              hasDNS=true
              release=pankaj
              statefulset.kubernetes.io/pod-name=pankaj-consul-server-0
Annotations:  consul.hashicorp.com/config-checksum: 914926d24d7bf77220ba40bb3625bc3103f9ddceb7042745eb0454d507be5706
              consul.hashicorp.com/connect-inject: false
Status:       Running
IP:           10.42.0.40
IPs:
  IP:           10.42.0.40
Controlled By:  StatefulSet/pankaj-consul-server
Containers:
  consul:
    Container ID:  containerd://e3c9fdf93032beeb204eed787abcae3ecfb7d1fd682c9fbbb1bc5a6fccb2327b
    Image:         hashicorp/consul:1.10.2
    Image ID:      docker.io/hashicorp/consul@sha256:8c6d8777e211920a0d939c723ab5b0bf5855ac88f5d3df0b5072601e4b973899
    Ports:         8500/TCP, 8301/TCP, 8301/UDP, 8302/TCP, 8302/UDP, 8300/TCP, 8600/TCP, 8600/UDP
    Host Ports:    0/TCP, 0/TCP, 0/UDP, 0/TCP, 0/UDP, 0/TCP, 0/TCP, 0/UDP
    Command:
      /bin/sh
      -ec
      CONSUL_FULLNAME="pankaj-consul"
      
      mkdir -p /consul/extra-config
      cp /consul/config/extra-from-values.json /consul/extra-config/extra-from-values.json
      [ -n "${HOST_IP}" ] && sed -Ei "s|HOST_IP|${HOST_IP?}|g" /consul/extra-config/extra-from-values.json
      [ -n "${POD_IP}" ] && sed -Ei "s|POD_IP|${POD_IP?}|g" /consul/extra-config/extra-from-values.json
      [ -n "${HOSTNAME}" ] && sed -Ei "s|HOSTNAME|${HOSTNAME?}|g" /consul/extra-config/extra-from-values.json
      
      exec /usr/local/bin/docker-entrypoint.sh consul agent \
        -advertise="${ADVERTISE_IP}" \
        -bind=0.0.0.0 \
        -bootstrap-expect=1 \
        -client=0.0.0.0 \
        -config-dir=/consul/config \
        -datacenter=dc1 \
        -data-dir=/consul/data \
        -domain=consul \
        -hcl="connect { enabled = true }" \
        -ui \
        -retry-join="${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
        -serf-lan-port=8301 \
        -config-file=/consul/extra-config/extra-from-values.json \
        -server
      
    State:          Running
      Started:      Wed, 06 Oct 2021 18:54:22 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:      100m
      memory:   100Mi
    Readiness:  exec [/bin/sh -ec curl http://127.0.0.1:8500/v1/status/leader \
2>/dev/null | grep -E '".+"'
] delay=5s timeout=5s period=3s #success=1 #failure=2
    Environment:
      ADVERTISE_IP:               (v1:status.podIP)
      HOST_IP:                    (v1:status.hostIP)
      POD_IP:                     (v1:status.podIP)
      NAMESPACE:                 default (v1:metadata.namespace)
      CONSUL_DISABLE_PERM_MGMT:  true
    Mounts:
      /consul/config from config (rw)
      /consul/data from data-default (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jv4zs (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  data-default:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-default-pankaj-consul-server-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      pankaj-consul-server-config
    Optional:  false
  kube-api-access-jv4zs:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  69s                default-scheduler  Successfully assigned default/pankaj-consul-server-0 to ip-172-31-37-34
  Normal   Pulled     69s                kubelet            Container image "hashicorp/consul:1.10.2" already present on machine
  Normal   Created    69s                kubelet            Created container consul
  Normal   Started    68s                kubelet            Started container consul
  Warning  Unhealthy  57s (x3 over 63s)  kubelet            Readiness probe failed:


`

**Comment by pankaj-dahiya** [comment] 2021-10-06 19:19
@lkysow are you able to replicate the same ?

**Comment by lkysow** [comment] 2021-10-08 16:14
Hi can you please follow our bug template and provide all the data we need to investigate:

1. Helm values
2. Helm versions, Kubernetes versions
3. The YAML for your service
4. The output of `kubectl get endpoints`
5. The logs of the connect inject deployment.

**Comment by lkysow** [comment] 2021-10-08 22:29
Thanks for the logs! Can you provide the YAML for your services or something similar so we could try and reproduce this ourselves?

**Comment by pankaj-dahiya** [comment] 2021-10-09 02:13
Which service YAML file do you need? I am using the original chart of consul-k8s and keycloak! I have enabled injector and reduced replica count to 1 in value.yaml

**Comment by lkysow** [comment] 2021-10-09 17:31
The keycloak install YAML.

**Comment by pankaj-dahiya** [comment] 2021-10-09 17:39
I am using the official keycloak helm chart without any changes:
https://github.com/codecentric/helm-charts/tree/master/charts/keycloak

FYI, I have tried the same with few other applications too, all giving the same error.!

**Comment by kschoche** [comment] 2021-10-12 14:05
Hi @pankaj-dahiya! I gave this a try on my end and I can see the same behaviour as you're reporting.
The reason that `connect-init` is stuck in a crash loop is that keycloak registers two Kubernetes services [`keycloak-headless`, `keycloak-http`] and we do not currently support a model where multiple kube services can reference the same pods in Consul.
I was able to work around it and get the `keycloak-http` service and pod to come online by deleting the `keycloak-headless` kube service and restarting the `keycloak` pod. I unfortunately do not know enough about keycloak to know what affect this will have on its behaviour as I don't know how to use keycloak.
You may want to give that a try and see if it works for you.
Also as a general note I noticed that even the `keycloak-http` service has 3 service ports and we currently only support a single service port in the mesh, so you may need to utilize 
https://www.consul.io/docs/k8s/connect#consul-hashicorp-com-transparent-proxy-exclude-inbound-ports
&& 
https://www.consul.io/docs/k8s/connect#consul-hashicorp-com-transparent-proxy-exclude-outbound-ports for the administrative ports, and these ports would not be utilizing the service mesh.

We do have support for multi-port services as well as managing situations where multiple kube services reference the same pods in our roadmap.

**Comment by kschoche** [comment] 2021-10-12 16:39
Hi @pankaj-dahiya - Unfortunately this is not possible in the current architecture. In theory an annotation to the k8s service object could be added and we could look at that when trying to manage consul service registration, however that would probably not be an ideal configuration anyways because you would have some ports of your service on the service mesh and some not on the service mesh.

**Comment by pankaj-dahiya** [comment] 2021-10-13 12:39
So does that mean, we should drop consul for at least this time, because the service mesh have such limitation which can't be overridden soon!

**Comment by pankaj-dahiya** [comment] 2021-10-13 16:32
@kschoche , you have specified above that consul can't register services if multiple services are pointing to a single pod, but we can see that the vault have multiple services with multiple ports, but its service is still registered!

**Comment by david-yu** [comment] 2021-12-08 18:37
Closing as this is related to multi-port services which is being tracked here: https://github.com/hashicorp/consul/issues/5388. As far as the case where multiple k8s services select the same pod, we are releasing a feature that allows you to ignore services via a `consul.hashicorp.com/service-ignore` label: https://github.com/hashicorp/consul-k8s/pull/858

**Closed by david-yu** 2021-12-08 18:37 UTC
Labels: question

**Comment by mister2d** [comment] 2022-02-25 18:45
> @kschoche , you have specified above that consul can't register services if multiple services are pointing to a single pod, but we can see that the vault have multiple services with multiple ports, but its service is still registered!

> Hi @pankaj-dahiya! Could you clarify your last comment a little bit please? I'm a little confused about mentioning `vault` for context of this discussion.

I believe `vault` was mentioned because Vault can register its services with Consul having multiple service on multiple ports, but not `keycloak`. For that matter, I am stuck trying to deploy a mariadb cluster with registered Consul services because it registers three services: `mariadb`, `mariadb-headless`, and `mariadb-galera-metrics`. Why would it work for Vault and not anything else (as far as I can tell)?
