### ISSUE TITLE
Consul Client stuck in pending state in k8s

### ISSUE THREAD

**Issue by dvpatel** [hashicorp/consul-k8s#1300] opened 2022-06-21 23:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Hi There,

I'm trying to install 2 different versions of Consul in 2 different K8s namespaces, ie. consul-blue and consul-green, for A/B type of an installation.  The problem I'm running into is the consul client remains in a pending state for installation in one of the namespaces, specifically consul-green namespace.  Also because the client is stuck in a pending state, kubectl logs produces no output.  Any guidance on next steps towards further diagnostics or resolution?

Thanks for your help.
-Dipesh

### Reproduction Steps

1.  I have 2 values which are passed into the helm install command:  values-blue.yaml and values-green.yaml

```
values-blue.yaml 


global:
  logLevel: "debug"
  image: "consul:1.11.3"
ui:
  enabled: true
  service:
    type: 'NodePort'
connectInject:
  enabled: false
controller:
  enabled: false
```

```
values-green.yaml 


global:
  logLevel: "debug"
  image: "consul:1.11.2"
ui:
  enabled: true
  service:
    type: 'NodePort'
connectInject:
  enabled: false
controller:
  enabled: false
```

```
helm install commands for installing 2 different Consul versions


helm install consul hashicorp/consul --create-namespace --namespace consul-blue --version "0.41.1" --values values-blue.yaml
helm install consul hashicorp/consul --create-namespace --namespace consul-green --version "0.40.0" --values values-green.yaml
```

### Logs

```
k8s pod status from command:  kubectl get pods --selector="component=client" -A 

NAMESPACE      NAME                         READY   STATUS    RESTARTS   AGE
consul-blue    consul-consul-client-7jkc6   1/1     Running   0          2m
consul-blue    consul-consul-client-jdqjk   1/1     Running   0          2m
consul-blue    consul-consul-client-zfrpr   1/1     Running   0          2m
consul-green   consul-consul-client-chkfs   0/1     Pending   0          117s
consul-green   consul-consul-client-cwnds   0/1     Pending   0          117s
consul-green   consul-consul-client-jwvh4   0/1     Pending   0          117s
```

```
No output from 'kubectl logs consul-consul-client-chkfs -n consul-green' 
```

```
Clean, valid output from 'kubectl logs consul-consul-client-7jkc6 -n consul-blue' 

2022-06-21T22:47:20.335Z [ERROR] agent.http: Request error: method=GET url=/v1/status/leader from=127.0.0.1:48834 error="No known Consul servers"
2022-06-21T22:47:27.335Z [INFO]  agent: Newer Consul version available: new_version=1.12.2 current_version=1.11.3
2022-06-21T22:47:30.336Z [WARN]  agent.router.manager: No servers available
2022-06-21T22:47:30.336Z [ERROR] agent.http: Request error: method=GET url=/v1/status/leader from=127.0.0.1:49124 error="No known Consul servers"
2022-06-21T22:47:31.250Z [WARN]  agent.router.manager: No servers available
2022-06-21T22:47:31.250Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
2022-06-21T22:47:40.238Z [WARN]  agent.router.manager: No servers available
2022-06-21T22:47:40.312Z [ERROR] agent.http: Request error: method=GET url=/v1/status/leader from=127.0.0.1:49314 error="No known Consul servers"
2022-06-21T22:47:46.024Z [INFO]  agent: (LAN) joining: lan_addresses=[consul-consul-server-0.consul-consul-server.consul-blue.svc:8301, consul-consul-server-1.consul-consul-server.consul-blue.svc:8301, consul-consul-server-2.consul-consul-server.consul-blue.svc:8301]
2022-06-21T22:47:46.033Z [INFO]  agent.client.serf.lan: serf: EventMemberJoin: consul-consul-server-0 10.244.171.133
2022-06-21T22:47:46.033Z [INFO]  agent.client: adding server: server="consul-consul-server-0 (Addr: tcp/10.244.171.133:8300) (DC: dc1)"
2022-06-21T22:47:46.038Z [INFO]  agent.client.serf.lan: serf: EventMemberJoin: consul-consul-server-1 10.244.71.71
2022-06-21T22:47:46.038Z [INFO]  agent.client: adding server: server="consul-consul-server-1 (Addr: tcp/10.244.71.71:8300) (DC: dc1)"
2022-06-21T22:47:46.042Z [INFO]  agent.client.serf.lan: serf: EventMemberJoin: dev-worker3 10.244.71.66
2022-06-21T22:47:46.042Z [INFO]  agent.client.serf.lan: serf: EventMemberJoin: consul-consul-server-2 10.244.184.74
2022-06-21T22:47:46.042Z [INFO]  agent: (LAN) joined: number_of_nodes=3
2022-06-21T22:47:46.042Z [INFO]  agent: Join cluster completed. Synced with initial agents: cluster=LAN num_agents=3
2022-06-21T22:47:46.042Z [INFO]  agent.client: adding server: server="consul-consul-server-2 (Addr: tcp/10.244.184.74:8300) (DC: dc1)"
2022-06-21T22:47:46.328Z [INFO]  agent.client.serf.lan: serf: EventMemberJoin: dev-worker 10.244.171.134
2022-06-21T22:47:48.813Z [INFO]  agent.client: New leader elected: payload=consul-consul-server-2
2022-06-21T22:47:49.014Z [INFO]  agent: Synced node info
```

### Expected behavior

Expected behavior is the ability to install and run multiple versions of Consul in K8s.

### Environment details

- Multiple versions of Consul, see configs above
- Kubernetes v1.24.0
- Kind / Docker Desktop for local development
- Calico CNI Plugin
- All running on local Mac

**Comment by ishustava** [comment] 2022-06-24 01:00
Hey @dvpatel 

We don't support deploying the chart in multiple k8s namespaces. Closing as this is a duplicate of #1232

**Closed by ishustava** 2022-06-24 01:00 UTC
Labels: type/bug
