### ISSUE TITLE
Failed to connect inject with Envoy

### ISSUE THREAD

**Issue by jojohappy** [hashicorp/consul-k8s#27] opened 2018-10-30 14:01 UTC
Hi,
  I try to install consul integrated with Kubernetes using consul-helm, and created a demo pod to test `Connect-inject`, but it was failed when it was `PodInitializing`.

The definition of pod is
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-server
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  containers:
    - name: static-server
      image: hashicorp/http-echo:latest
      args:
        - -text="hello world"
        - -listen=:8080
      ports:
        - containerPort: 8080
          name: http
```

The error log is
```
Error registering service "static-server-proxy": Put http://<host_ip>:8500/v1/agent/service/register: dial tcp <host_ip>:8500: connect: connection refused
```
I saw that the `ip` requested was the kubernetes node ip address, but I did not setup the consul client daemonset to use `hostNetwork: true`, so I have a question why inject container setup the `CONSUL_HTTP_ADDR` as `HOST_IP`? After that I updated the daemonset to use `hostNetwork`, it worked well. 

I found the code, maybe we could optimize that. Or could you tell me whats wrong I did? Thank you.
https://github.com/hashicorp/consul-k8s/blob/0c6dede68a44d5d4ca48c5522b2e05f5ea1322a2/connect-inject/container_init.go#L70-L99

**Comment by adilyse** [comment] 2018-11-16 22:36
@jojohappy Could you give a bit more detail about the kubernetes environment that you're using? 

There's been a [similar issue](https://github.com/hashicorp/consul-helm/issues/43) on EKS, that AWS has potentially fixed now. It would be good to know if your issue is in the same environment and if it's still happening.

**Comment by jojohappy** [comment] 2018-11-19 08:32
@adilyse Thank you for your reply, but I don't build my Kubernetes on EKS. It just relies on several EC2 instances and I use the flannel networking. I guess the `hostPort` does not work for my cluster.

**Comment by lkysow** [comment] 2019-09-19 00:09
This issue is quite old so I'm going to close it but if you still have this problem please comment and we'll re-open.

**Closed by lkysow** 2019-09-19 00:09 UTC

**Comment by MK1985** [comment] 2019-12-06 11:23
the problem still exists

**Comment by lkysow** [comment] 2019-12-06 18:10
@MK1985 we need more information to debug. Are all your Consul agents up and running?

**Comment by 7imbrook** [comment] 2020-01-14 04:05
Seeing this issue on digitaloceans k8s clusters as well. I've narrowed it down to loopback interfaces not being configured on boot. Due to this being managed by DO (in my case) I can't enable it. @MK1985 I hope that maybe sheds some light.

**Comment by lkysow** [comment] 2020-01-16 23:12
@7imbrook this might be the same root cause of https://github.com/hashicorp/consul-helm/issues/327 which is due to this cilium bug: https://github.com/cilium/cilium/issues/9784

As a workaround, try setting
```
     dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
```

in your client daemonset.
