### ISSUE TITLE
Warning at installation and up-gradation of the chart.

### ISSUE THREAD

**Issue by pankaj-dahiya** [hashicorp/consul-k8s#1281] opened 2022-06-15 13:35 UTC
coalesce.go:202: warning: destination for image is a table. Ignoring non-table value hashicorp/consul:1.12.0

**Comment by pankaj-dahiya** [comment] 2022-06-16 02:06
I don't think any of the above things are required!!
Just pull the latest helm chart and do helm install. You will see the warning!

**Comment by david-yu** [comment] 2022-07-28 23:03
Closing as unable to reproduce.

**Closed by david-yu** 2022-07-28 23:03 UTC
Labels: type/bug, waiting-reply
