### ISSUE TITLE
Nodes and dead services remaining in the consul catalog

### ISSUE THREAD

**Issue by Stephani0106** [hashicorp/consul-k8s#2065] opened 2023-04-18 18:43 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

We noticed that the issue began to occur in our dev environment, and later in qas, after the adoption of spot instances within our Kubernetes cluster (AKS). We don't rule out the possibility that the mistake has always happened, but we don't notice it as often as we do now.

Because they are machines with idle capacity, sometimes some of our nodes were killed because the machine was "stolen" by Azure, however our environment whenever it identified these node deaths recreated them with new names to always keep a minimum number of nodes available in the environment.

Our issue within the consul began to be identified just when there were these node deaths. When a node is killed, the Consul does not deregister it from the catalog even though it no longer exists within the cluster. This ends up causing "ghost" services to remain in the Consul catalog with failure status even though they no longer exist.

This results in dead service instances in the Consul catalog and healthcheck issues, for example.

![image](https://user-images.githubusercontent.com/73966290/232870056-d8a7b662-c0ae-4045-bd7d-c6b4ac62b11f.png)

### Palliative solution

As a palliative solution to work around the problem, we manually removed dead services from the catalog. For this we open a shell in one of the pods of the Consul server and execute the request below:

```bash
curl http://127.0.0.1:8500/v1/catalog/service/<service-name> | jq
```
After making sure that the node in fact no longer exists in the cluster, we run the command below to unregister all the services present in that node:

```bash
curl --request PUT -d '{"Node":"<node-name>"}' http://127.0.0.1:8500/v1/catalog/deregister
```

This solves the problem temporarily, but every time a node is killed or recreated the problem recurs and again we need to perform the steps above.

### Expected behavior

We expected Consul to deregister all nodes and services that did not respond properly to healthcheck, thus excluding dead services from its catalog.

### Environment details

The version of Consul-k8s in our environment that presents the issue goes from the v1.0.4 and App Version 1.14.4 to v1.1.1 of chart and App Version 1.15.1.
This is because, we identified the error in version 1.0.4 and after upgrading to version 1.1.1 the error persists.

The version of Kubernetes we used goes from 1.24.6 to 1.25.5.

### Additional Context

The issue #1817 presents a very similar case with what we find in our environment.

**Comment by andrewnazarov** [comment] 2023-06-01 13:10
We have kinda the same situation when we have nodes upgrade in GKE. Our use case might be a bit different, because we don't have the K8s synchronisation enabled - the registration and deregistration both are handled by our apps exclusively. However, we also have a timeout when a service gets registered forcefully if it's not terminated correctly or the app wasn't able to deregister itself correctly during shutdown. What we do see in common with this though is that we have unhealthy nodes after the k8s upgrade and unhealthy services too which cannot be deregistered due to the timeout because the node is red.

I was wondering if `terminationGracePeriodSeconds` could be configured for Consul client pods to mitigate this if it were the case. But I don't see the setting in the chart.

**Comment by FelipeEmerim** [comment] 2023-06-20 13:44
This is a bigger problem than it seems to be. If the dead service's IP overlaps with a live service IP, envoy will create a passthrough cluster for the dead service and drop the connection. This is common in kubenet setups where pods use an internal network.  Every time a node is removed we see dead services in Consul. In some cases as described in this issue, in other cases as in #2085.  

This makes Consul very difficult to work with in spot environments and every cluster upgrade problematic. @andrewnazarov suggested tweaking `terminationGracePeriodSeconds` in the client nodes, but consul-k8s dropped client nodes after v1.0.0. Is there any other workaround on this issue?

**Comment by david-yu** [comment] 2023-07-20 21:33
Closing as the PR that addresses this is now merged: https://github.com/hashicorp/consul-k8s/pull/2571. This should be released in 1.2.x, 1.1.x, and 1.0.x by mid August timeframe for our next set of patch releases.

**Closed by david-yu** 2023-07-20 21:33 UTC
Labels: type/bug

**Comment by andrewnazarov** [comment] 2023-09-07 09:58
Version 1.1.4 didn't solve our problem. Still experiencing dead nodes and services.

**Comment by komapa** [comment] 2023-11-03 16:52
1.2.x did not solve it for us either. We have 2000+ virtual nodes when our cluster is only 28 nodes right now.

**Comment by david-yu** [comment] 2023-11-03 20:47
Could you test with the latest versions of Consul as well? If this still is an issue, we should perhaps re-open but we need more information on how to reproduce. I believe K8s 1.26 and above actually helps solve this issue with graceful node shutdown: https://kubernetes.io/blog/2023/08/16/kubernetes-1-28-non-graceful-node-shutdown-ga/#:~:text=The%20Graceful%20Node%20Shutdown%20feature,a%20non%2Dgraceful%20node%20shutdown.

**Comment by MageshSrinivasulu** [comment] 2024-03-01 17:06
Facing the same issue with k8s 1.27 as well

**Comment by MageshSrinivasulu** [comment] 2024-07-31 05:53
Still facing the same issue with k8s 1.28 as well, using consul 1.16.6. If the Consul cannot provide a solution, please provide a documented workaround. This seems to be a never-ending issue.

**Comment by akrymets** [comment] 2024-11-27 22:29
Still facing this issue using consul 1.19.1.
I remember it since version 1.4.4 with no changes

**Comment by alealh** [comment] 2025-02-07 16:29
Same issue using consul 1.20.2 with Azure Kubernetes Service.
Is there any workaround?

**Comment by Stephani0106** [comment] 2025-02-10 11:14
Here, we ended up changing our service mesh tool. 
But we don't know if there is a workaround for the problem since we stopped using Consul.

**Comment by csyyysc** [comment] 2026-05-12 00:50
Is this issue really solved? I only use Nomad + Consul, and realized that those not unregistered services names still exist under `consul catalog services`, and this even cannot be cleaned up through any commands or even restart the consul services itself, and what left is to remove the data under /opt/consul/data which is extremely dangerous under production mode, and I think this originated from the Consul itself. I use consul version V1.20.5.

Oh my bad, i was not giving agent policy token for ACL, so the consul remains stale because of blocked by ACLs. This is solved, thanks.
